# Generated by Django 4.1 on 2023-06-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JiraApp", "0003_label_issue_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(
                choices=[
                    ("High", "High"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("Story", "Story"),
                    ("Spillover", "Spillover"),
                ],
                max_length=50,
            ),
        ),
    ]
