# Generated by Django 4.1 on 2023-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JiraApp", "0004_alter_label_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "open"),
                    ("assigned", "assigned"),
                    ("in_progress", "in_progress"),
                    ("under_review", "under_review"),
                    ("done", "done"),
                    ("close", "close"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
