# Generated by Django 4.1 on 2023-06-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("JiraApp", "0007_sprint_issue_sprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="sprint",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="JiraApp.sprint",
            ),
        ),
    ]
