# Generated by Django 4.1 on 2023-06-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("JiraApp", "0010_alter_issue_assignee_alter_issue_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="JiraApp.sprint",
            ),
        ),
    ]
