# Generated by Django 4.1 on 2023-06-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("JiraApp", "0011_alter_issue_sprint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="comment",
        ),
        migrations.AddField(
            model_name="issue",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="JiraApp.comment",
            ),
        ),
    ]
