# Generated by Django 4.1 on 2023-06-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("JiraApp", "0014_rename_issue_id_comment_issue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="issue",
        ),
        migrations.AddField(
            model_name="issue",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="JiraApp.comment",
            ),
        ),
    ]
