# Generated by Django 4.1 on 2023-06-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JiraApp", "0015_rename_comment_comment_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="addedBy",
        ),
    ]
